/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                   '#f2ca50',
        'on-primary':                '#3c2f00',
        'primary-container':         '#d4af37',
        'primary-fixed':             '#ffe088',
        'primary-fixed-dim':         '#e9c349',
        'on-primary-fixed':          '#241a00',
        'on-primary-fixed-variant':  '#574500',
        'on-primary-container':      '#554300',
        'secondary':                 '#c8c6c5',
        'on-secondary':              '#313030',
        'secondary-container':       '#474746',
        'on-secondary-container':    '#b7b5b4',
        'secondary-fixed':           '#e5e2e1',
        'secondary-fixed-dim':       '#c8c6c5',
        'on-secondary-fixed':        '#1c1b1b',
        'on-secondary-fixed-variant':'#474746',
        'tertiary':                  '#cecece',
        'on-tertiary':               '#2f3131',
        'tertiary-container':        '#b2b3b3',
        'on-tertiary-container':     '#444546',
        'tertiary-fixed':            '#e2e2e2',
        'tertiary-fixed-dim':        '#c6c6c7',
        'on-tertiary-fixed':         '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        'error':                     '#ffb4ab',
        'on-error':                  '#690005',
        'error-container':           '#93000a',
        'on-error-container':        '#ffdad6',
        'background':                '#131313',
        'on-background':             '#e4e2e1',
        'surface':                   '#131313',
        'on-surface':                '#e4e2e1',
        'surface-variant':           '#353535',
        'on-surface-variant':        '#d0c5af',
        'surface-dim':               '#131313',
        'surface-bright':            '#393939',
        'surface-container-lowest':  '#0e0e0e',
        'surface-container-low':     '#1b1c1c',
        'surface-container':         '#1f2020',
        'surface-container-high':    '#2a2a2a',
        'surface-container-highest': '#353535',
        'inverse-surface':           '#e4e2e1',
        'inverse-on-surface':        '#303030',
        'inverse-primary':           '#735c00',
        'outline':                   '#99907c',
        'outline-variant':           '#4d4635',
        'surface-tint':              '#e9c349',
      },
      borderRadius: {
        DEFAULT: '0px',
        sm:      '0px',
        md:      '0px',
        lg:      '0px',
        xl:      '0px',
        '2xl':   '0px',
        '3xl':   '0px',
        full:    '9999px',
      },
      spacing: {
        'margin-desktop': '80px',
        'margin-mobile':  '24px',
        'section-gap':    '160px',
        'gutter':         '32px',
        'stack-unit':     '8px',
      },
      fontFamily: {
        'display-lg':         ['"Libre Caslon Text"', 'serif'],
        'headline-lg':        ['"Libre Caslon Text"', 'serif'],
        'headline-lg-mobile': ['"Libre Caslon Text"', 'serif'],
        'headline-md':        ['"Libre Caslon Text"', 'serif'],
        'label-caps':         ['"Hanken Grotesk"', 'sans-serif'],
        'body-md':            ['"Hanken Grotesk"', 'sans-serif'],
        'body-lg':            ['"Hanken Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'display-lg':         ['72px',  { lineHeight: '80px',  letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg':        ['48px',  { lineHeight: '56px',  fontWeight: '400' }],
        'headline-lg-mobile': ['32px',  { lineHeight: '40px',  fontWeight: '400' }],
        'headline-md':        ['32px',  { lineHeight: '40px',  fontWeight: '400' }],
        'label-caps':         ['12px',  { lineHeight: '16px',  letterSpacing: '0.15em', fontWeight: '600' }],
        'body-md':            ['16px',  { lineHeight: '24px',  fontWeight: '400' }],
        'body-lg':            ['18px',  { lineHeight: '28px',  fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
